### ISSUE TITLE
android 5.0 seems not work

### ISSUE THREAD

**Issue by jackyang0317** [akexorcist/ScreenshotDetection#1]
android 5.0 onScreenCapturedWithDeniedPermission & onScreenCaptured are not triggered

**Comment by akexorcist** [comment]
I tested it on my LG Nexus 4 (Android 5.1.1) and it worked fine.

This issue was opened for a year so I will closed this issue. Sorry for lately reply.

Who has same problem. Feel free to re-open this issue and provide more device information (brand and model)
