### ISSUE TITLE
Hello, I found that after denying the storage permission, the screenshot will call the onScreenCapturedWithDeniedPermission method twice.

### ISSUE THREAD

**Issue by MRDHR** [akexorcist/ScreenshotDetection#4]
Hello, I found that after denying the storage permission, the screenshot will call the onScreenCapturedWithDeniedPermission method twice. After the permission is granted, the onScreenCaptured method is called only once.
sorry for my pool english

![image](https://user-images.githubusercontent.com/5576916/123913709-1c2bbf80-d9b1-11eb-9fd6-973814bde099.png)
![image](https://user-images.githubusercontent.com/5576916/123913808-3a91bb00-d9b1-11eb-8b69-fc3fb44392b2.png)

**Comment by akexorcist** [comment]
Refer to #5, `onScreenCapturedWithDeniedPermission` method not suitable in that case. Remove it might be the solution. So I will remove it in next version.
