### ISSUE TITLE
onScreenCapturedWithDeniedPermission may be incorrect

### ISSUE THREAD

**Issue by Lewin671** [akexorcist/ScreenshotDetection#5]
Hi, I have seen all the source codes of this project, and I notice that `onScreenCapturedWithDeniedPermission` may cause some unexpected results. 

For example, if the external disk is put something new, then you will detect a new file and invoke `onContentChanged`, but it's actually not the screen capture.

**Comment by akexorcist** [comment]
This seem removing `onScreenCapturedWithDeniedPermission` might be the solution for this case. Because we cannot check the actual path of file without permission.
